Kochiev sergej konstantinovich
ISUCT/Informatics_2022 pull request #106
Opened 2022-11-11 22:02 UTC by sergeykochiev

2022-11-16 06:30 UTC, jskonst requested changes

2022-11-16 06:30 UTC, jskonst commented on python/Pipfile
> +astroid = "==2.12.12"
Зачем?

2022-11-16 06:30 UTC, jskonst commented on python/Pipfile
> +dill = "==0.3.5.1"
Зачем?

2022-11-16 06:30 UTC, jskonst commented on python/Pipfile
> +mccabe = "==0.7.0"
Зачем?

2022-11-16 06:30 UTC, jskonst commented on python/Pipfile
> +platformdirs = "==2.5.2"
Зачем?

2022-11-16 06:30 UTC, jskonst commented on python/Pipfile
> +pylint = "==2.15.5"
а добавили к скриптам эти проверки?

2022-11-16 06:30 UTC, jskonst commented on python/Pipfile
> +wrapt = "==1.14.1"
А зачем? (все вопросы зачем - можно просто ответить - интересно зачем все это вам сейчас)

2022-11-16 06:30 UTC, jskonst commented on python/src/main.py
> +
Так мы уже на функции переехали - преобразуйте в функции

2022-11-16 06:36 UTC, sergeykochiev commented on python/Pipfile
> +wrapt = "==1.14.1"
если имеете ввиду зачем оно в реквесте - я не знаю. случайно добавил, не удалил

2022-11-16 06:37 UTC, sergeykochiev commented on python/src/main.py
> +
хорошо

2022-11-16 06:50 UTC, sergeykochiev commented on python/src/main.py
> +
видел люди делают перебор как отдельную функцию, это обязательно?

2022-11-16 06:52 UTC, sergeykochiev commented on python/Pipfile
> +wrapt = "==1.14.1"
если имеете ввиду зачем я это установил - тоже не знаю, само в процессе настройки поставилось...

2022-11-16 09:58 UTC, jskonst commented on python/src/main.py
> +
потом будет да

2022-11-16 09:59 UTC, jskonst commented on python/Pipfile
> +wrapt = "==1.14.1"
удалите плиз тогда - иначе каждый раз будет тянуться

2022-11-16 10:33 UTC, sergeykochiev commented
я запутался

2022-11-16 10:44 UTC, sergeykochiev commented
теперь все норм?

2022-11-23 21:02 UTC, jskonst requested changes

2022-11-23 21:02 UTC, jskonst commented on python/src/main.py
> +    print(function(n))
Это уже можете выносить в отдельные функции

2022-11-23 21:03 UTC, jskonst requested changes

2022-11-23 21:03 UTC, jskonst commented on python/src/main.py
> +print("Задача 1:")
ну или как минимум этот код переносится под if

2022-11-27 18:01 UTC, merged