Added tests + solved tasks from Codewars
ISUCT/Informatics_2022 pull request #145
Opened 2022-11-16 10:39 UTC by EugeneWWolf

Группа 1/147
Файл main_test.go пришлось положить в одну директорию с main.go, потому что иначе нельзя было вызвать тестируемую функцию в файле main_test.go, когда он лежал в директории tests.

Дополнение к заданию по Codewars'у: имена некоторых функций из примеров пришлось поменять, так как линтер ругался на неиспользуемую функцию.

2022-11-23 21:44 UTC, jskonst commented
> 

можно - если функцию назвать с большой буквы

2022-11-23 21:46 UTC, jskonst requested changes

2022-11-23 21:46 UTC, jskonst commented on golang/main_test.go
> +package main
Тесты все же давайте перенесем - вам пример надо показать

2022-11-23 21:46 UTC, jskonst commented on golang/main_test.go
> +package main
совместно порешаем - пинганите в дискорде

2022-11-23 21:46 UTC, jskonst commented on golang/main.go
> +func EvenOrOdd(number int) string {
Это уже можно переносить на раздельные функции

2022-11-23 21:48 UTC, jskonst commented on golang/main.go
> +// Это задание нельзя было выполнить на Go на Codewars, поэтому написала для него тесты в main_test.go
👍

2022-11-24 09:15 UTC, EugeneWWolf commented on golang/main.go
> +func EvenOrOdd(number int) string {
Что можно вынести в отдельную функцию? Раздробить функцию с формулой на более мелкие?

В итоге после правок получится супер-мешанина из кодов в комитах, попробую с этим что-то сделать

2022-11-24 09:17 UTC, EugeneWWolf commented on golang/main_test.go
> +package main
Хорошо, ближе к вечеру пингану и опишу проблему, если не получится её решить

2022-11-24 18:58 UTC, closed without merging