Лаб1, разделила задачи на разные функции
ISUCT/Informatics_2022 pull request #159
Opened 2022-11-21 12:37 UTC by Mary2811

Я не сообразила, что  нужно написать в return, поэтому написала "1", программа конечно работает, но что-то мне подсказывает, что это очень неправильно

2022-11-23 17:58 UTC, Mary2811 commented
я случайно закинула в этот пул реквест 5 задач, и еще меня поломала задача с овцами. В codewars все проходит, а здесь на моменте if value == true все ломается. Поэтому я немного испортила код и все bool поменяла на string

2022-11-23 22:14 UTC, jskonst commented on golang/main.go
> -func main() {
Задачу A и B нужно вернуть

2022-11-23 22:15 UTC, jskonst requested changes
Задачу a и b верните

2022-11-27 18:45 UTC, jskonst requested changes

2022-11-27 18:45 UTC, jskonst commented on golang/lab1.go
> +	fmt.Println("Задание А")
не надо тут выводить - перенесите на строчку до вызова этой функции

2022-11-27 18:45 UTC, jskonst commented on golang/lab1.go
> +		fmt.Println("x = ", x, " ", "y = ", function(a, x))
Не выводите тут в консоль - верните значения

2022-11-27 18:45 UTC, jskonst commented on golang/lab1.go
> +	return (1)
вот прям так себе - другой разработчик будет ожидать результат, а ему всегда будет возвращаться 1

2022-11-27 18:45 UTC, jskonst commented on golang/lab1.go
> +	fmt.Println("Задание B")
аналогично

2022-11-27 18:45 UTC, jskonst commented on golang/main.go
> +	fmt.Println(zadacha1(a), zadacha2(a))
не надо так :) - тем боле что у вас сейчас эти функции должны будут возвращать значения

2022-11-27 19:26 UTC, Mary2811 commented on golang/main.go
> +	fmt.Println(zadacha1(a), zadacha2(a))
чего-то я совсем не поняла, как тут нужно выводить. Я сделала return в функциях и теперь не понимаю, как правильно выводить

2022-11-27 19:35 UTC, jskonst commented on golang/main.go
> +	fmt.Println(zadacha1(a), zadacha2(a))
а тут либо просто Print того что функция вернула
либо перебрать значения и также выводить по строчкам

2022-11-27 19:57 UTC, Mary2811 commented on golang/main.go
> +	fmt.Println(zadacha1(a), zadacha2(a))
что-то я все равно какую-то ерунду наделала, даже как-то стыдно

2022-11-29 20:06 UTC, jskonst commented on golang/main.go
> +	fmt.Println(zadacha1(a), zadacha2(a))
Это нормально

2022-11-29 20:07 UTC, jskonst commented on golang/lab1.go
> +	for x := 1.2; x < 4.2; x = x + 0.6 {
```suggestion
	for x := xn; x < xk; x += dx {
```

2022-11-29 20:08 UTC, jskonst requested changes

2022-11-29 20:08 UTC, jskonst commented on golang/lab1.go
> +func zadacha1(a float64) []float64 {
```suggestion
func zadacha1(a, xn, xk,dx float64) []float64 {
```

2022-11-29 20:08 UTC, jskonst commented on golang/main.go
> +	fmt.Println("Задача 1")
лучше бы их не Задача 1 - а можно прям имя с codewars

2022-11-29 20:08 UTC, jskonst commented
Почти все ок

2022-11-29 20:26 UTC, jskonst approved these changes

2022-11-29 20:26 UTC, merged