LabFuncV8
ISUCT/Informatics_2022 pull request #166
Opened 2022-11-24 15:57 UTC by AlyonaUi

2022-11-27 19:05 UTC, jskonst commented on golang/Work/codewars.go
> +package main
а зачем перенесли во вложенную папку?

2022-11-27 19:09 UTC, jskonst requested changes

2022-11-27 19:09 UTC, jskonst commented on golang/Work/codewars.go
> +	k := 0
🔕 не используйте однобуквенные переменные

2022-11-27 19:09 UTC, jskonst commented on golang/main.go
> +	y := (math.Pow(b, 3) + math.Pow(math.Sin(a*x), 2)) / (math.Acos(x*b*x) + (math.Pow(e, -x/2)))
а вот тут дублирование кода
вынесите `y := (math.Pow(b, 3) + math.Pow(math.Sin(a*x), 2)) / (math.Acos(x*b*x) + (math.Pow(e, -x/2)))` в отдельную функцию

2022-11-27 19:09 UTC, jskonst commented on golang/main.go
> +		y := par2(1.2, 0.48, 2.72, x)
В модуле Math есть функция exp() - которая возведет e в указанную в скобках степень с гораздо лучшей точностью

2022-11-28 12:15 UTC, AlyonaUi commented on golang/Work/codewars.go
> +	k := 0
Спасибо, поняла. Исправлю.

2022-11-28 12:15 UTC, AlyonaUi commented on golang/Work/codewars.go
> +package main
Я подумала что будет удобно скидывать туда все работы.

2022-11-29 20:41 UTC, jskonst commented on golang/Work/codewars.go
> +package main
да - но потом :) , но в любом случае не надо 2 main

2022-11-29 20:42 UTC, jskonst commented on golang/main.go
> +		y := par(1.2, 0.48, x)
уже можете выделять в отдельные функции

2022-12-02 18:35 UTC, jskonst requested changes
в целом почти все

2022-12-02 18:35 UTC, jskonst commented on golang/main.go
> +        fmt.Println(par(a, b, x))
почти - тут надо значение возвращать (точнее функция будет возвращать список значений

2022-12-05 17:07 UTC, merged