Все задачи с Codewars + тесты в отдельной директории + улучшение кода (теперь мой код на вычисление алгебраической функции умеет работать с аргументами командной строки)
ISUCT/Informatics_2022 pull request #168
Opened 2022-11-24 19:04 UTC by EugeneWWolf

Группа 1/147

Edit 30.11: Теперь мой код работает с аргументами запуска. Если ничего не вводить, то программа запустится со стандартными значениями. Аргументы запуска можно увидеть, напечатав `go run main.go -h`

Edit 02.12: Залила в отдельный файл все решения задач с Codewars, которые вы присылали в дискорде

2022-11-24 19:26 UTC, jskonst commented on golang/go.mod
> +module myProject
вот это в целом не влияет - просто отсчет ведется от isuct.ru/informatics2022
и то что у вас стало myProject/internal должно было бы быть isuct.ru/informatics2022/internal

2022-11-24 19:29 UTC, jskonst commented on golang/internal/functions.go
> +}
Это уж какая-то микрооптимизация :) смысла нет

2022-11-24 19:29 UTC, jskonst commented on golang/tests/functions_test.go
> +func TestEvaluateFunctionTableDriven(t *testing.T) {
для ассертов - https://github.com/stretchr/testify#assert-package
Это упростит код

2022-11-24 19:30 UTC, jskonst commented on golang/tests/functions_test.go
> +		{0.4, 0.8, 3.2, "0.991503"},
правило, которого стоит придерживаться - 1 тест 1 кейс

2022-11-24 19:30 UTC, jskonst commented on golang/tests/functions_test.go
> +	for _, testInput := range tests {
не надо вам все тестировать - 1 полложительный - а дальше - краевые случаи, даже если задачей у вас они не обозначены

2022-11-24 19:32 UTC, jskonst commented on golang/main.go
> +		internal.PrintFunctionValue(x, internal.EvaluateFunction(a, b, x))
Задачи А и Б вытаскивайте в отдельные функции
а вот тесты на них - только то что они размер массива правильный вернут

2022-11-25 23:53 UTC, EugeneWWolf commented on golang/tests/functions_test.go
> +		{0.4, 0.8, 3.2, "0.991503"},
Переделала тесты с помощью ассертов, но не уверена, соблюла ли я правило 1 тест 1 кейс. Скорее всего, мой код можно сделать чище и читабельнее.
Старалась написать как можно лучше, но мне нужен сон.

2022-11-26 09:37 UTC, EugeneWWolf commented
Постаралась сделать код более "универсальным", теперь он может принимать пользовательский ввод. Но код выглядит так, будто его надо отрефакторить позже.

2022-11-27 19:30 UTC, jskonst requested changes
Оч хорошо - но надо еще улучшить

2022-11-27 19:30 UTC, jskonst commented on golang/internal/functions.go
> +func PrintFunctionValue(functionValue *[]float64) {
если у нас это срез то он уже указатель

2022-11-27 19:30 UTC, jskonst commented on golang/main.go
> +	var a, b float64
лучше сразу все же присваивайте значения

2022-11-27 19:30 UTC, jskonst commented on golang/main.go
> +	fmt.Println("Task A: please, input a, b, start value for x, end value for x and step for x") // Указатели сделаны, чтобы передавать в функции слайс
не совсем и можно было и не передавать как указатель - там копия только заголовка
https://stackoverflow.com/questions/39993688/are-slices-passed-by-value

2022-11-27 19:30 UTC, jskonst commented on golang/tests/functions_test.go
> +	testValues := testsEvaluateFunction{a: 0.4, b: 0.8, x: 3.2, want: "0.991503"}
не надо приводить к строке - потом используйте https://pkg.go.dev/github.com/stretchr/testify/assert#InDelta

2022-11-27 19:30 UTC, jskonst commented on golang/tests/functions_test.go
> +	assert.Equal(testValues.want, fmt.Sprintf("%.6f", functionValue), "Want and got should be equal.")
```suggestion
	assert.Equal(testValues.want, fmt.Sprintf("%.6f", functionValue),  fmt.Sprintf("expected: %d got: %d", testValues.want, functionValue ))
```

2022-11-27 19:30 UTC, jskonst commented on golang/tests/functions_test.go
> +	functionValue, err = internal.EvaluateFunction(testValues.a, testValues.b, testValues.x)
1 тест - проверка только 1 случая - это у вас еще + 2 функции тестов

2022-11-27 19:30 UTC, jskonst commented on golang/tests/functions_test.go
> +func TestSolveTaskB(t *testing.T) {
Для задач а и б достаточно проверить просто длины массивов + тесты на неправильные параметры

2022-11-28 12:40 UTC, EugeneWWolf commented on golang/main.go
> +	var a, b float64
У пользователя есть возможность самостоятельно вводить начальное и конечное значение для переменной x, для параметров a и b, поэтому нельзя определить их сразу. В коде значения задаются через fmt.Scan и указатели.

2022-11-29 20:45 UTC, jskonst commented on golang/main.go
> +	var a, b float64
не надо - в ближайшее время мы с пользовательским вводом не работаем
а если будет нужно - то эту логику работы с пользовательским вводом надо выносить отдельно

2022-11-29 20:47 UTC, jskonst commented on golang/internal/functions.go
> +	for i := 0; i < size; i++ {
можно было for range

2022-11-29 20:49 UTC, jskonst requested changes

2022-11-29 20:49 UTC, jskonst commented on golang/main.go
> +	var startValueForX, endValueForX, step float64
по хорошему  - это надо выносить из main'а
кероме того - еще раз повторюсь - не надо пока нам
по факту сейчас редко работают вот так интерактивно - скорее через аргументы запуска, конфигарации, переменные окружения

2022-11-30 12:31 UTC, EugeneWWolf commented
Теперь программа при запуске будет работать с заранее заданными значениями. Но если пользователь хочет, то он может присвоить значение false флагу d (go run main.go -d=false) и он сможет интерактивно ввести свои произвольные значения.

(Я оставила интерактивный ввод, так как переписывать прогу практически полностью долго, но если будет время, я попытаюсь ради практики сделать произвольный ввод значений с помощью флагов)

**Переделала код (см. ниже)**

2022-12-02 17:40 UTC, jskonst commented on golang/go.mod
> +require github.com/stretchr/testify v1.8.1 // indirect
👍

2022-12-02 17:46 UTC, jskonst approved these changes

2022-12-02 17:46 UTC, merged