Tests
ISUCT/Informatics_2022 pull request #172
Opened 2022-11-27 18:11 UTC by Fuflick

2022-11-27 18:17 UTC, jskonst commented on CourseApp.Tests/DemoTest.cs
> +            {
зачем доп скобки?
во всех остальных тоже надо убрать

2022-11-27 18:33 UTC, jskonst requested changes

2022-11-27 18:33 UTC, jskonst commented on CourseApp/Task.cs
> +        }
🔕 
вот эта функция не должна быть публичной

2022-11-27 18:33 UTC, jskonst commented on CourseApp.Tests/DemoTest.cs
> +                var t = Task.Znamen(1.1);
По идее знаменатель проверяется через вызов функции Alg

2022-11-27 18:33 UTC, jskonst commented on CourseApp.Tests/DemoTest.cs
> +                Assert.NotEqual(0, t);
при вычислениях нужно проверить соответствиее определенному числу

2022-11-27 18:33 UTC, jskonst commented on CourseApp.Tests/DemoTest.cs
> +        private void Test2()
старайтесь в имени указать что тест проверяет
https://github.com/stretchr/testify

2022-11-27 18:33 UTC, jskonst commented on CourseApp.Tests/DemoTest.cs
> +            var t = Task.TaskA(1.28, 3.28, 0.4);
что будет если а или b = 0 ?
что будет при отрицательном х ?

2022-11-27 18:33 UTC, jskonst commented on CourseApp/Program.cs
> +            var t = Task.TaskA(1.28, 3.28, 0.4);
🔕 не используйте нетипичные однобуквенные переменные

2022-11-27 18:33 UTC, jskonst commented on CourseApp/Program.cs
> +            Console.ReadLine();
вот это не обязательно

2022-11-27 18:33 UTC, jskonst commented on CourseApp/Task.cs
> +            for (double x = startx; x <= finx; x += deltx)
```suggestion
            for (double x = startx; x <= finx; x += deltax)
```

2022-11-27 18:33 UTC, jskonst commented on CourseApp/Task.cs
> +            for (double x = startx; x <= finx; x += deltx)
```suggestion
            for (double x = startX; x <= finX; x += deltaX)
```

2022-11-28 16:44 UTC, Fuflick commented on CourseApp/Task.cs
> +        }
а вот проблемка вылезла, у меня при вызове
 private функции пишется, что функцию вызвать нельзя из-за уровня защиты

2022-11-29 20:52 UTC, jskonst commented on CourseApp.Tests/DemoTest.cs
> +        /*
любой закомментированный код - удаляйте

2022-11-29 20:55 UTC, jskonst requested changes

2022-11-29 20:55 UTC, jskonst commented on CourseApp/Task.cs
> +        public static double[] GetZnamen
а зачем он вообще вам? вы ж его не используете - вроме непосредственно функции ALG - ну и кроме того с чего вдруг он массив?

2022-11-29 20:55 UTC, jskonst commented on CourseApp/Task.cs
> +            }
Это вам точно не надо

2022-11-29 20:55 UTC, jskonst commented on CourseApp/Task.cs
> +        public static double[] GetZnamen
а вот остальное - в целом ок

2022-12-07 11:21 UTC, closed without merging