Добавила новые задачи с codewars
ISUCT/Informatics_2022 pull request #176
Opened 2022-11-30 13:55 UTC by Mary2811

добавила 2 задачи из 3, так как не смогла написать код для задачи с двумерным массивом, не совсем понимаю как в go работать с ним

2022-12-02 18:37 UTC, jskonst requested changes

2022-12-02 18:37 UTC, jskonst commented on golang/codewars.go
> +func findAll(n int, massiv []int) []int {
была еще 1 задача?

2022-12-02 18:37 UTC, jskonst commented on golang/codewars.go
> +func findAll(n int, massiv []int) []int {
да - сумма минимальных в матрице

2022-12-02 18:37 UTC, jskonst commented
> добавила 2 задачи из 3, так как не смогла написать код для задачи с двумерным массивом, не совсем понимаю как в go работать с ним

Это как массив (срез) содержащий в себе в качестве элементов срезы - двойным циклом

2022-12-02 20:06 UTC, Mary2811 commented on golang/codewars.go
> +func findAll(n int, massiv []int) []int {
я добавила код для этой задачи, но не поняла, почему не заработало с типом int, в интернете прочитала, что стоит заменить на uint, и все заработало, но я не совсем поняла, чем они отличаются

2022-12-05 17:52 UTC, jskonst commented
> добавила 2 задачи из 3, так как не смогла написать код для задачи с двумерным массивом, не совсем понимаю как в go работать с ним

представьте что у вас есть одномерный массив - в котором каждый элемент - это еще массив

2022-12-05 17:56 UTC, Mary2811 commented
> > добавила 2 задачи из 3, так как не смогла написать код для задачи с двумерным массивом, не совсем понимаю как в go работать с ним
> 
> представьте что у вас есть одномерный массив - в котором каждый элемент - это еще массив

да, я поняла и добавила код для этой задачи с массивами, но не поняла поему она не работала у меня с типом массива int, а с uint заработала

2022-12-05 18:07 UTC, jskonst commented on golang/codewars.go
> +func findAll(n int, massiv []int) []int {
uint - unsigned

2022-12-05 18:14 UTC, Mary2811 commented on golang/codewars.go
> +func findAll(n int, massiv []int) []int {
изменила все uint обратно на int и все работает, видимо в первый раз ошибка была в другом месте

2022-12-05 18:16 UTC, jskonst approved these changes

2022-12-05 18:17 UTC, merged