golang&python -> CSharp
ISUCT/Informatics_2022 pull request #94
Opened 2022-11-11 18:53 UTC by Fuflick

Lab count

2022-11-11 20:07 UTC, jskonst commented
Так - больше не переоткрываете PR - еще раз его переоткроете - не буду проверять - все ж комменты слетают приходится заново каждый файл пересматривать

2022-11-11 20:09 UTC, jskonst requested changes

2022-11-11 20:09 UTC, jskonst commented on README.md
> +<<<<<<< HEAD
А зачем вам в Readme артефакты неправильного merge'a ?

2022-11-12 05:56 UTC, Fuflick commented on README.md
> +<<<<<<< HEAD
remade

2022-11-16 06:11 UTC, jskonst commented on CourseApp/Program.cs
> +    internal class Program : Task
не надо вам тут наследоваться

2022-11-16 06:17 UTC, merged

2022-11-18 09:31 UTC, Fuflick commented on CourseApp/Program.cs
> +    internal class Program : Task
Я пытался импортировать функцию из класса Alg и у меня постоянно выходила ошибка
видимо я с модификаторами доступа накосячил, но работать код у меня стал только так. 
Я сейчас попробую разобраться, но если что я вам в лс напишу.

2022-11-18 09:44 UTC, Fuflick commented on CourseApp/Program.cs
> +    internal class Program : Task
Я поправил, хз, почему не работало до этого