Hello
ISUCT/Informatics_2022 pull request #96
Opened 2022-11-11 19:31 UTC by HalizovaAnna

2022-11-11 20:13 UTC, jskonst commented
Неа - что за файлы? которые не запустить?

2022-11-11 20:13 UTC, jskonst requested changes

2022-11-11 20:13 UTC, jskonst commented on Hello
> +print("Hello world!")
Это надо переделать

2022-11-11 22:05 UTC, HalizovaAnna commented on Hello
> +print("Hello world!")
Здравствуйте, я переделала лабораторную по функциям

2022-11-16 06:20 UTC, jskonst commented on Hello
> +print("Hello world!")
А вот не вижу - этого файла не должно быть

2022-11-16 06:20 UTC, jskonst requested changes

2022-11-16 06:20 UTC, jskonst commented on Laba20.py
> +#A
Файлы надо размещать в соответствующих каталогах - переностие внутрь golang - рядом с main или в него самого

2022-12-06 18:29 UTC, closed without merging